a=input("nhập chuỗi s1:")
b=input("nhập chuỗi s2:")
c=input("nhập chuỗi s3:")
d=input("nhập index:")
print("chiều dài chuỗi s1=",len(a))
print("chiều dài chuỗi s2=",len(b))
print("chiều dài chuỗi s3=",len(c))
print("chuỗi s4 =",a[d:])
print("chuỗi s2 lập lại 2 lần",b*2)